### ISSUE TITLE
Initialise the client-side routes

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#13]
We may need to have a parent component (can be done within the App.jsx) which will contain the `react-router-dom` routes for our client.
There may not need to have any routes set up just yet as the routes will be added by each component ticket.
For now just get the client-side ready to utilise routes for the components.

Tasks: 
- [x] Install necessary npm packages
- [x] Add `Router` to project
- [x] Ensure `App` component has access to `BrowserRouter` and `Link` for when needed

- [ ] Estimate completion of the task - 1 hr**

** = not sure

**Comment by Eteroa123** [comment]
Kia ora brothers !!!!!

Ive been assigned ticket #19  and just letting you all know that when you finish let me know and ill add my component route! 

Cheers
