### ISSUE TITLE
Create a Login component

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#14]
Our users need a way to login to our app. Let's start by creating a login component that may just require a username, password and then a button to login. This component may need to communicate with the database/auth to login.
You may also need to ensure that this component has a client-side route set up too.

Tasks:
- [x]   Check the [wiki](https://github.com/kahikatea-2019/MOA/wiki) for relevant information.
- [x]   Create component file.
- [x]   Create log in form for users to enter their details.
- [x]   Create client-side route for component.
- [x] Write tests for this component.

You won't need to do any design just yet, just the basics to get this showing.

**Comment by struanw** [comment]
Expect to review at 3:30pm on 2nd May.
