### ISSUE TITLE
Create a Header Component

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#19]
When we display the dashboard of a user we want to also display their Name, Surname, Cohort and Role. So we will need to create a header component to go within the dashboard component.

It's also a good idea to create some mock data to utilise within this component. Having the mock data set up in the same format as the wiki ensures that the real live data we send through later will be even more seamless to integrate.

_Think about whether this is likely to be functional or class based._ 

You may also need to ensure that this component has a client-side route set up too. 

Tasks:
- [x] Check the [wiki](https://github.com/kahikatea-2019/MOA/wiki) for relevant information.
- [x] Create component file. 
- [x] Create mock data which is in the same shape as the wiki and used within the component
- [x] Write tests for this component.

You won't need to do any design just yet, just the basics to get this showing.

_Ensure that the component is utilising the mock data the same way it will when it is fully connected - i.e. from an object (to later be replaced by `props`), rather than just hardcoded into the `render` method._

**Comment by Eteroa123** [comment]
My estimation for this ticket is till 5pm.

**Comment by Eteroa123** [comment]
"jest -o --coverage" -- this was used in order to help me with testing my component.
