### ISSUE TITLE
Create ProgressModule Component

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#21]
When we display the dashboard of a user we want to also display their progress for each module. So we will need to create a ProgressModule component to go within the dashboard component.

It's also a good idea to create some mock data to utilise within this component. Having the mock data set up in the same format as the wiki ensures that the real live data we send through later will be even more seamless to integrate.

_Think about whether this is likely to be functional or class based._  _Also think if how this component will be used, will we want to map data into this component?_

You may also need to ensure that this component has a client-side route set up too. 

Tasks:
- [x] Check the [wiki](https://github.com/kahikatea-2019/MOA/wiki) for relevant information.
- [x] Create component file. 
- [x] Create mock data which is in the same shape as the wiki and used within the component.
- [x] Display header component within the dashboard. 
- [x] Create client-side route for component. 
- [x] Write tests for this component.

You won't need to do any design just yet, just the basics to get this showing.

**Comment by MurdocAV** [comment]
I'm happy to start this component, won't include any css stylings

**Comment by MurdocAV** [comment]
Starting Time: 2:38pm 

- Creating it as ~~a functional component (> class)~~ Switched to **class** component
- Going to test with mock data, will try make integration seamless before finishing

**Comment by MurdocAV** [comment]
Going to pause progress on this to work on a more important ticket, realized the order of the numbers matter.

**Comment by MurdocAV** [comment]
I am taking a break from this module and going to work on some server side requests because It's more easy to conceptualize. 

**For anyone who is picking up this ticket**
- I have comments on how I was thinking.
- Feel free to edit the code in anyway you see fit, no offence will be taken and no ownership is mine.

**Comment by MurdocAV** [comment]
Mock Data completed.

**Comment by MurdocAV** [comment]
Got mock data working, Didn't write initial tests. Going to implement tests and refactor.

**Comment by MurdocAV** [comment]
Tests written and passing

**Comment by MurdocAV** [comment]
Looking for reviewer feedback for what to improve, update or do next. Will try to look through redux implementation for now
