### ISSUE TITLE
Create DropDown component

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#22]
When we display the dashboard of a user we want to also display their progress for each assessment of each module. So we will need to create a DropDown component to go within the dashboard component. We thought that this could be a dropdown, however, we could go for something else if it works better.

It's also a good idea to create some mock data to utilise within this component. Having the mock data set up in the same format as the wiki ensures that the real live data we send through later will be even more seamless to integrate.

_Think about whether this is likely to be functional or class based._  _Also think if how this component will be used, will we want to map data into this component?_

You may also need to ensure that this component has a client-side route set up too. 

Tasks:
- [ ] Check the [wiki](https://github.com/kahikatea-2019/MOA/wiki) for relevant information.
- [ ] Create component file. 
- [ ] Create mock data which is in the same shape as the wiki and used within the component.
- [ ] Display DropDown component within the Dashboard component. 
- [ ] Create client-side route for component. 
- [ ] Write tests for this component.

You won't need to do any design just yet, just the basics to get this showing.

**Comment by Anandani11** [comment]
4 hours.
