### ISSUE TITLE
Create the seeds

### ISSUE THREAD

**Issue by emilyparkes** [kahikatea-2019/MOA#26]
This is a **very important** component of the back-end. 

You will need to setup your tables and fields to be in-line with that data model within the [wiki](https://github.com/kahikatea-2019/MOA/wiki/Data-Model).

Tasks: 
- [x] Create seeds.

**Comment by MurdocAV** [comment]
Should take no more than 45-75 minutes.
Edit: added 30 minutes for extra time
Current Eta: 12:05am

Changes on 'Students_Assessments' .id(PK) incremented from 1-4 rather than 1 for all id's

**Comment by MurdocAV** [comment]
Completed: Time - 11:53am
