### ISSUE TITLE
Create a GET route to get the assessments from the DB

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#5]
We will need to be able to feed our Assessment Content to the client-side of our application.

Create a GET route which feeds this content via our API, something like /assessments could work.

Tasks:
- [x] Refer to the [wiki](https://github.com/kahikatea-2019/EDAMAME/wiki/Server-Routes) to see how the routes may need to be setup.
- [x] Create the route.
- [x] Create db function.
- [x] Write tests for this route.
- [x] Write tests for db function.

**Comment by mxbialostocki** [comment]
Estimated completion time 1500 03/05/2019
