### ISSUE TITLE
Create a PUT route to update a users assessment with evidence in the DB

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#6]
Our users will be wanting to submit evidence that they've completed an assessment.
Create a PUT route which allows them to do so. 

 Tasks: 
- [ ] Refer to the [wiki](https://github.com/kahikatea-2019/MOA/wiki/Server-Routes) to see how the routes may need to be setup.
- [ ] Create route.
- [ ] Create db function.
- [ ] Write tests for this route.
- [ ] Write tests for db function.

**Comment by paul-renwick** [comment]
Estimated time 2 hours.
