### ISSUE TITLE
Create a GET route to get a particular cohort from the DB

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#8]
We need to have a server route to display a list of students for a particular cohort and send the data back.

Tasks: 
- [ ] Refer to the [wiki](https://github.com/kahikatea-2019/MOA/wiki/Server-Routes) to see how the routes may need to be setup.
- [ ] Create route.
- [ ] Create db function.
- [ ] Write test for this route.
- [ ] Write test for db function.

**Comment by paul-renwick** [comment]
Estimated time 3 hours

**Comment by chrislaupama** [comment]
@paul-renwick I'm going to close this for now, and have the app currently focus on a students view for now
